/* ============================================================================
 * responsibilities-data2.js
 * ----------------------------------------------------------------------------
 * Continuation of the rule-8 tables: fluid, flexible, structured, highly
 * structured. Registered onto RESPONSIBILITIES.RESP via registerResp().
 * Uses the same concise builders exposed on RESP_BUILD.
 * ==========================================================================*/

(function (global) {
  'use strict';

  var B = global.RESP_BUILD;
  var P = B.P, Pd = B.Pd, R = B.R, Rd = B.Rd, Rl = B.Rl, Du = B.Du, Dul = B.Dul;

  // ---------------------------------------------------------------- FLUID -----
  var FLUID = {
    contain: [
      P('GK', 'Shield Goal'),
      R('Sweeper Keeper', 'Limit Pressure'),
      P('SW', 'Obstruct Shots'),
      R('Libero', 'Restrict Space Cautiously'),
      P('DC', 'Obstruct Shots'),
      Du('Stopper', 'Divert Attacking Movement'),
      P('DL', 'Slow Attacking Movement'),
      P('DM', 'Contain Attacking Movement'),
      P('WBL', 'Divert Attacking Movement'),
      P('MC', 'Disrupt Attacks'),
      R('Box to Box Midfielder', 'Restrict Space Aggressively'),
      R('Deep Lying Playmaker', 'Restrict Space Cautiously'),
      Du('Defend', 'Restrict Space Cautiously'),
      P('ML', 'Disrupt Attacks Quickly'),
      P('AMC', 'Recover Possession After Defensive Transition'),
      R('Advanced Playmaker', 'Disrupt Attacks Quickly'),
      R('Shadow Striker', 'Recover Possession Immediately'),
      P('AML', 'Recover Possession'),
      Rl('Advanced Forward', true, 'Recover Possession Immediately'),
      Dul('Attack', false, 'Keep Possession Under Pressure'),
      Rl('False Nine', true, 'Recover Possession After Defensive Transition'),
      Dul('Support', false, 'Recover Possession'),
      Dul('Defend', false, 'Recover Possession'),
      Rl('Trequartista', true, 'Recover Possession After Defensive Transition'),
      Rl('Trequartista', false, 'Keep Possession Away From Pressure')
    ],
    defensive: [
      P('GK', 'Limit Pressure'),
      R('Sweeper Keeper', 'Distribute Safely'),
      P('SW', 'Contain Attacking Movement'),
      R('Libero', 'Disrupt Attacks Judiciously'),
      P('DC', 'Divert Attacking Movement'),
      Du('Cover', 'Contain Attacking Movement'),
      Du('Stopper', 'Restrict Space Aggressively'),
      P('DL', 'Restrict Space Cautiously'),
      P('DM', 'Restrict Space'),
      R('Half Back', 'Restrict Space Cautiously'),
      P('WBL', 'Restrict Space Aggressively'),
      P('MC', 'Recover Possession'),
      R('Box to Box Midfielder', 'Disrupt Attacks Quickly'),
      R('Deep Lying Playmaker', 'Restrict Space Aggressively'),
      Du('Defend', 'Disrupt Attacks Judiciously'),
      P('ML', 'Recover Possession Immediately'),
      P('AMC', 'Keep Possession Away From Pressure'),
      R('Advanced Playmaker', 'Recover Possession Immediately'),
      R('Shadow Striker', 'Keep Possession Under Pressure'),
      P('AML', 'Keep Possession'),
      Rl('Advanced Forward', true, 'Keep Possession Under Pressure'),
      Dul('Attack', false, 'Shuttle Ball Through Defence'),
      Rl('False Nine', true, 'Keep Possession Away From Pressure'),
      Dul('Support', false, 'Keep Possession'),
      Rl('Trequartista', true, 'Keep Possession Away From Pressure'),
      Rl('Trequartista', false, 'Shuttle Ball Into Space')
    ],
    counter: [
      P('GK', 'Limit Pressure'),
      R('Sweeper Keeper', 'Cycle Possession'),
      P('SW', 'Restrict Space Cautiously'),
      R('Libero', 'Recover Possession After Defensive Transition'),
      P('DC', 'Restrict Space Aggressively'),
      Du('Cover', 'Restrict Space Cautiously'),
      Du('Stopper', 'Disrupt Attacks'),
      P('DL', 'Disrupt Attacks Judiciously'),
      P('DM', 'Disrupt Attacks'),
      R('Half Back', 'Restrict Space Aggressively'),
      P('WBL', 'Disrupt Attacks Quickly'),
      P('MC', 'Keep Possession'),
      R('Box to Box Midfielder', 'Recover Possession Immediately'),
      R('Deep Lying Playmaker', 'Disrupt Attacks'),
      Du('Defend', 'Recover Possession After Defensive Transition'),
      P('ML', 'Keep Possession Under Pressure'),
      P('AMC', 'Shuttle Ball Into Space'),
      R('Advanced Playmaker', 'Keep Possession Under Pressure'),
      R('Shadow Striker', 'Shuttle Ball Through Defence'),
      P('AML', 'Shuttle Ball'),
      Rl('Advanced Forward', true, 'Shuttle Ball Through Defence'),
      Dul('Attack', false, 'Spearhead Attacking Moves'),
      Rl('False Nine', true, 'Shuttle Ball Into Space'),
      Dul('Support', false, 'Shuttle Ball Into Space'),
      Rl('Trequartista', true, 'Shuttle Ball Into Space'),
      Rl('Trequartista', false, 'Shuttle Ball Through Defence')
    ],
    standard: [
      P('GK', 'Distribute Safely'),
      R('Sweeper Keeper', 'Cycle Possession'),
      P('SW', 'Restrict Space Aggressively'),
      R('Libero', 'Recover Possession Immediately'),
      P('DC', 'Disrupt Attacks'),
      Du('Cover', 'Restrict Space Aggressively'),
      Du('Stopper', 'Recover Possession After Defensive Transition'),
      P('DL', 'Disrupt Attacks Quickly'),
      P('DM', 'Recover Possession After Defensive Transition'),
      R('Half Back', 'Disrupt Attacks'),
      P('WBL', 'Recover Possession'),
      P('MC', 'Shuttle Ball Into Space'),
      R('Box to Box Midfielder', 'Keep Possession'),
      R('Deep Lying Playmaker', 'Recover Possession After Defensive Transition'),
      Du('Defend', 'Recover Possession Immediately'),
      P('ML', 'Shuttle Ball'),
      P('AMC', 'Shuttle Ball Through Defence'),
      R('Advanced Playmaker', 'Shuttle Ball'),
      R('Shadow Striker', 'Spearhead Attacking Moves'),
      P('AML', 'Spearhead Attacking Moves from the Hole'),
      Rd('Defensive Winger', 'Defend', 'Suppress Counterattacking Options'),
      Du('Support', 'Create Chances Patiently'),
      Rl('Advanced Forward', true, 'Spearhead Attacking Moves'),
      Dul('Attack', false, 'Penetrate Gaps Intermittently'),
      Rl('Defensive Forward', true, 'Suppress Counterattacks'),
      Rl('False Nine', true, 'Shuttle Ball Through Defence'),
      Rl('Trequartista', true, 'Shuttle Ball Through Defence'),
      Rl('Trequartista', false, 'Create Chances')
    ],
    control: [
      P('GK', 'Cycle Possession'),
      R('Sweeper Keeper', 'Initiate Attacks'),
      P('SW', 'Disrupt Attacks'),
      R('Libero', 'Keep Possession'),
      P('DC', 'Recover Possession After Defensive Transition'),
      Du('Cover', 'Disrupt Attacks'),
      Du('Stopper', 'Recover Possession Immediately'),
      P('DL', 'Recover Possession'),
      P('DM', 'Recover Possession Immediately'),
      R('Half Back', 'Recover Possession After Defensive Transition'),
      P('WBL', 'Keep Possession Away From Pressure'),
      P('MC', 'Shuttle Ball Through Defence'),
      R('Box to Box Midfielder', 'Shuttle Ball Into Space'),
      R('Deep Lying Playmaker', 'Recover Possession Immediately'),
      Du('Defend', 'Keep Possession'),
      P('ML', 'Spearhead Attacking Moves from the Hole'),
      Rd('Defensive Winger', 'Defend', 'Suppress Counterattacking Options'),
      Du('Support', 'Create Chances Patiently'),
      P('AMC', 'Spearhead Attacking Moves'),
      R('Advanced Playmaker', 'Shuttle Ball Through Defence'),
      R('Shadow Striker', 'Penetrate Gaps Intermittently'),
      P('AML', 'Spearhead Attacking Moves Closer to Defence'),
      Rl('Advanced Forward', true, 'Penetrate Gaps Intermittently'),
      Dul('Attack', false, 'Penetrate Gaps Persistently'),
      Rl('Defensive Forward', true, 'Isolate Advancing Midfielders'),
      Rl('Defensive Forward', false, 'Suppress Counterattacks'),
      Rl('False Nine', true, 'Create Chances'),
      Rl('Trequartista', true, 'Create Chances'),
      Rl('Trequartista', false, 'Force Chances When Necessary')
    ],
    attacking: [ // guide labels this "ATTACK" under Fluid
      P('GK', 'Cycle Possession'),
      R('Sweeper Keeper', 'Initiate Attacks'),
      P('SW', 'Recover Possession'),
      R('Libero', 'Shuttle Ball'),
      P('DC', 'Keep Possession Away From Pressure'),
      Du('Cover', 'Recover Possession After Defensive Transition'),
      Du('Stopper', 'Keep Possession'),
      P('DL', 'Keep Possession'),
      P('DM', 'Keep Possession Under Pressure'),
      R('Half Back', 'Keep Possession Away From Pressure'),
      P('WBL', 'Shuttle Ball Into Space'),
      P('MC', 'Spearhead Attacking Moves Closer to Defence'),
      R('Box to Box Midfielder', 'Create Chances Patiently'),
      R('Deep Lying Playmaker', 'Keep Possession Under Pressure'),
      Du('Defend', 'Shuttle Ball'),
      Du('Support', 'Create Chances Urgently'),
      P('ML', 'Penetrate Gaps Intermittently'),
      P('AMC', 'Penetrate Gaps'),
      R('Advanced Playmaker', 'Create Chances Urgently'),
      R('Enganche', 'Force Half Chances'),
      R('Shadow Striker', 'Penetrate Gaps Persistently'),
      R('Trequartista', 'Force Half Chances'),
      P('AML', 'Penetrate Gaps Persistently'),
      Rd('Defensive Winger', 'Defend', 'Isolate Holding Midfielders'),
      Rl('Advanced Forward', true, 'Draw Off Defenders'),
      Dul('Attack', false, 'Overload Defenders'),
      Rl('Defensive Forward', true, 'Hassle Dawdling Defenders'),
      Rl('Defensive Forward', false, 'Isolate Advancing Midfielders'),
      Rl('False Nine', true, 'Force Half Chances')
    ],
    overload: [
      P('GK', 'Initiate Attacks'),
      R('Sweeper Keeper', 'Support Attacks'),
      P('SW', 'Keep Possession'),
      Rd('Libero', 'Attack', 'Spearhead Attacking Moves'),
      Rd('Libero', 'Support', 'Create Chances'),
      P('DC', 'Shuttle Ball Into Space'),
      Du('Cover', 'Keep Possession Away From Pressure'),
      Du('Stopper', 'Shuttle Ball'),
      P('DL', 'Shuttle Ball'),
      P('DM', 'Shuttle Ball Through Defence'),
      R('Half Back', 'Shuttle Ball Into Space'),
      P('WBL', 'Spearhead Attacking Moves from the Hole'),
      Du('Defend', 'Suppress Counterattacking Options'),
      Du('Support', 'Create Chances Patiently'),
      P('MC', 'Penetrate Gaps Persistently'),
      R('Advanced Playmaker', 'Force Half Chances Without Hesitation'),
      R('Box to Box Midfielder', 'Force Half Chances When Necessary'),
      R('Deep Lying Playmaker', 'Shuttle Ball Through Defence'),
      P('ML', 'Draw Off Defenders'),
      P('AMC', 'Overload Defenders'),
      R('Enganche', 'Test Defence'),
      R('Trequartista', 'Test Defence'),
      P('AML', 'Challenge Defenders'),
      Rd('Defensive Winger', 'Defend', 'Hassle Defenders Relentlessly'),
      Rl('Advanced Forward', true, 'Bypass Last Defender'),
      Dul('Attack', false, 'Bypass Last Defender'),
      Rl('Defensive Forward', true, 'Force Clearance'),
      Rl('Defensive Forward', false, 'Hassle Dawdling Defenders'),
      Rl('False Nine', true, 'Test Defence')
    ]
  };

  // ------------------------------------------------------------- FLEXIBLE -----
  var FLEXIBLE = {
    contain: [
      P('GK', 'Shield Goal'),
      R('Sweeper Keeper', 'Limit Pressure'),
      P('SW', 'Obstruct Shots'),
      Rd('Libero', 'Attack', 'Restrict Space Aggressively'),
      Rd('Libero', 'Support', 'Divert Attacking Movement'),
      P('DC', 'Obstruct Shots'),
      Du('Stopper', 'Divert Attacking Movement'),
      P('DL', 'Disrupt Attacks Judiciously'),
      Du('Defend', 'Slow Attacking Movement'),
      Du('Support', 'Restrict Space Cautiously'),
      P('DM', 'Contain Attacking Movement'),
      P('WBL', 'Disrupt Attacks Quickly'),
      Rd('Wing Back', 'Defend', 'Divert Attacking Movement'),
      Rd('Wing Back', 'Support', 'Restrict Space Aggressively'),
      P('MC', 'Recover Possession After Defensive Transition'),
      Rd('Deep Lying Playmaker', 'Support', 'Restrict Space'),
      P('ML', 'Recover Possession'),
      P('AMC', 'Recover Possession Immediately'),
      Rd('Advanced Playmaker', 'Attack', 'Recover Possession After Defensive Transition'),
      Rd('Advanced Playmaker', 'Support', 'Disrupt Attacks Judiciously'),
      R('Shadow Striker', 'Keep Possession'),
      P('AML', 'Keep Possession Away From Pressure'),
      Rd('Defensive Winger', 'Defend', 'Disrupt Attacks Judiciously'),
      Rl('Advanced Forward', true, 'Keep Possession'),
      Dul('Attack', false, 'Shuttle Ball'),
      Rl('Defensive Forward', true, 'Disrupt Attacks'),
      Rl('False Nine', true, 'Recover Possession After Defensive Transition'),
      Rl('Trequartista', true, 'Recover Possession Immediately'),
      Rl('Trequartista', false, 'Keep Possession Under Pressure')
    ],
    defensive: [
      P('GK', 'Limit Pressure'),
      Rd('Sweeper Keeper', 'Attack', 'Distribute Safely'),
      Rd('Sweeper Keeper', 'Support', 'Limit Pressure'),
      P('SW', 'Contain Attacking Movement'),
      Rd('Libero', 'Attack', 'Disrupt Attacks Quickly'),
      Rd('Libero', 'Support', 'Restrict Space Aggressively'),
      P('DC', 'Divert Attacking Movement'),
      Du('Cover', 'Contain Attacking Movement'),
      Du('Stopper', 'Restrict Space Aggressively'),
      P('DL', 'Recover Possession After Defensive Transition'),
      Du('Defend', 'Restrict Space Cautiously'),
      Du('Support', 'Disrupt Attacks Judiciously'),
      P('DM', 'Restrict Space'),
      R('Half Back', 'Restrict Space Cautiously'),
      P('WBL', 'Recover Possession Immediately'),
      Rd('Wing Back', 'Defend', 'Restrict Space Aggressively'),
      Rd('Wing Back', 'Support', 'Disrupt Attacks Quickly'),
      P('MC', 'Keep Possession Away From Pressure'),
      Rd('Deep Lying Playmaker', 'Defend', 'Restrict Space Aggressively'),
      Rd('Deep Lying Playmaker', 'Support', 'Disrupt Attacks'),
      P('ML', 'Keep Possession'),
      P('AMC', 'Keep Possession Under Pressure'),
      Rd('Advanced Playmaker', 'Attack', 'Keep Possession Away From Pressure'),
      Rd('Advanced Playmaker', 'Support', 'Recover Possession After Defensive Transition'),
      R('Shadow Striker', 'Shuttle Ball'),
      P('AML', 'Shuttle Ball Into Space'),
      Rd('Defensive Winger', 'Defend', 'Recover Possession After Defensive Transition'),
      Rl('Advanced Forward', true, 'Shuttle Ball'),
      Dul('Attack', false, 'Spearhead Attacking Moves'),
      Rl('Defensive Forward', true, 'Recover Possession'),
      Rl('False Nine', true, 'Recover Possession Immediately'),
      Rl('Trequartista', true, 'Keep Possession Under Pressure'),
      Rl('Trequartista', false, 'Shuttle Ball Through Defence')
    ],
    counter: [
      P('GK', 'Limit Pressure'),
      Rd('Sweeper Keeper', 'Attack', 'Cycle Possession'),
      Rd('Sweeper Keeper', 'Support', 'Distribute Safely'),
      P('SW', 'Restrict Space Cautiously'),
      Rd('Libero', 'Attack', 'Recover Possession'),
      Rd('Libero', 'Support', 'Disrupt Attacks'),
      P('DC', 'Restrict Space'),
      Du('Cover', 'Divert Attacking Movement'),
      Du('Stopper', 'Disrupt Attacks Judiciously'),
      P('DL', 'Recover Possession Immediately'),
      Du('Defend', 'Restrict Space Aggressively'),
      Du('Support', 'Disrupt Attacks Quickly'),
      P('DM', 'Disrupt Attacks Judiciously'),
      R('Half Back', 'Restrict Space'),
      P('WBL', 'Keep Possession'),
      Rd('Wing Back', 'Defend', 'Disrupt Attacks'),
      Rd('Wing Back', 'Support', 'Recover Possession'),
      P('MC', 'Keep Possession Under Pressure'),
      Rd('Deep Lying Playmaker', 'Defend', 'Disrupt Attacks'),
      Rd('Deep Lying Playmaker', 'Support', 'Recover Possession After Defensive Transition'),
      P('ML', 'Shuttle Ball Into Space'),
      P('AMC', 'Shuttle Ball'),
      Rd('Advanced Playmaker', 'Attack', 'Keep Possession Under Pressure'),
      Rd('Advanced Playmaker', 'Support', 'Recover Possession Immediately'),
      R('Shadow Striker', 'Spearhead Attacking Moves from the Hole'),
      P('AML', 'Shuttle Ball Through Defence'),
      Rd('Defensive Winger', 'Defend', 'Recover Possession Immediately'),
      Rl('Advanced Forward', true, 'Spearhead Attacking Moves from the Hole'),
      Dul('Attack', false, 'Spearhead Attacking Moves Closer to Defence'),
      Rl('Defensive Forward', true, 'Keep Possession Away From Pressure'),
      Rl('False Nine', true, 'Keep Possession'),
      Rl('Trequartista', true, 'Shuttle Ball'),
      Rl('Trequartista', false, 'Create Chances Patiently')
    ],
    standard: [
      P('GK', 'Distribute Safely'),
      R('Sweeper Keeper', 'Cycle Possession'),
      P('SW', 'Restrict Space'),
      Rd('Libero', 'Attack', 'Keep Possession Away From Pressure'),
      Rd('Libero', 'Support', 'Recover Possession After Defensive Transition'),
      P('DC', 'Disrupt Attacks Judiciously'),
      Du('Cover', 'Restrict Space'),
      Du('Stopper', 'Disrupt Attacks Quickly'),
      P('DL', 'Keep Possession'),
      Du('Defend', 'Disrupt Attacks'),
      Du('Support', 'Recover Possession'),
      P('DM', 'Disrupt Attacks Quickly'),
      R('Half Back', 'Disrupt Attacks Judiciously'),
      P('WBL', 'Shuttle Ball Into Space'),
      Rd('Wing Back', 'Defend', 'Recover Possession After Defensive Transition'),
      Rd('Wing Back', 'Support', 'Keep Possession Away From Pressure'),
      P('MC', 'Shuttle Ball'),
      Rd('Deep Lying Playmaker', 'Defend', 'Disrupt Attacks Quickly'),
      Rd('Deep Lying Playmaker', 'Support', 'Recover Possession Immediately'),
      P('ML', 'Shuttle Ball Through Defence'),
      P('AMC', 'Spearhead Attacking Moves from the Hole'),
      Rd('Advanced Playmaker', 'Attack', 'Shuttle Ball'),
      Rd('Advanced Playmaker', 'Support', 'Keep Possession'),
      R('Shadow Striker', 'Spearhead Attacking Moves Closer to Defence'),
      P('AML', 'Spearhead Attacking Moves'),
      Rd('Defensive Winger', 'Defend', 'Keep Possession'),
      Rl('Advanced Forward', true, 'Spearhead Attacking Moves Closer to Defence'),
      Dul('Attack', false, 'Penetrate Gaps'),
      Rl('Defensive Forward', true, 'Keep Possession Under Pressure'),
      Rl('False Nine', true, 'Shuttle Ball Into Space'),
      Rl('Trequartista', true, 'Create Chances Patiently'),
      Rl('Trequartista', false, 'Create Chances Urgently')
    ],
    control: [
      P('GK', 'Distribute Safely'),
      Rd('Sweeper Keeper', 'Attack', 'Initiate Attacks'),
      Rd('Sweeper Keeper', 'Support', 'Cycle Possession'),
      P('SW', 'Disrupt Attacks Judiciously'),
      Rd('Libero', 'Attack', 'Keep Possession Under Pressure'),
      Rd('Libero', 'Support', 'Recover Possession Immediately'),
      P('DC', 'Disrupt Attacks Quickly'),
      Du('Cover', 'Disrupt Attacks Judiciously'),
      Du('Stopper', 'Recover Possession'),
      P('DL', 'Shuttle Ball Into Space'),
      Du('Defend', 'Recover Possession After Defensive Transition'),
      Du('Support', 'Keep Possession Away From Pressure'),
      P('DM', 'Recover Possession'),
      R('Half Back', 'Disrupt Attacks Quickly'),
      P('WBL', 'Shuttle Ball Through Defence'),
      Rd('Wing Back', 'Defend', 'Recover Possession Immediately'),
      Rd('Wing Back', 'Support', 'Keep Possession Under Pressure'),
      P('MC', 'Spearhead Attacks from the Hole'),
      Rd('Deep Lying Playmaker', 'Defend', 'Recover Possession'),
      Rd('Deep Lying Playmaker', 'Support', 'Keep Possession'),
      P('ML', 'Spearhead Attacks'),
      P('AMC', 'Spearhead Attacks Closer to Defence'),
      Rd('Advanced Playmaker', 'Attack', 'Create Chances Patiently'),
      Rd('Advanced Playmaker', 'Support', 'Shuttle Ball Into Space'),
      R('Shadow Striker', 'Penetrate Gaps'),
      P('AML', 'Penetrate Gaps Intermittently'),
      Rd('Defensive Winger', 'Defend', 'Shuttle Ball Into Space'),
      Rl('Advanced Forward', true, 'Penetrate Gaps'),
      Dul('Attack', false, 'Draw Off Defenders'),
      Rl('Defensive Forward', true, 'Shuttle Ball'),
      Rl('False Nine', true, 'Shuttle Ball Through Defence'),
      Rl('Trequartista', true, 'Create Chances Urgently'),
      Rl('Trequartista', false, 'Force Half Chances')
    ],
    attacking: [
      P('GK', 'Cycle Possession'),
      R('Sweeper Keeper', 'Initiate Attacks'),
      P('SW', 'Disrupt Attacks Quickly'),
      Rd('Libero', 'Attack', 'Shuttle Ball'),
      Rd('Libero', 'Support', 'Keep Possession'),
      P('DC', 'Recover Possession'),
      Du('Cover', 'Disrupt Attacks'),
      Du('Stopper', 'Recover Possession Immediately'),
      P('DL', 'Shuttle Ball Through Defence'),
      Du('Defend', 'Recover Possession Immediately'),
      Du('Support', 'Keep Possession Under Pressure'),
      P('DM', 'Keep Possession Away From Pressure'),
      R('Half Back', 'Recover Possession'),
      P('WBL', 'Spearhead Attacks'),
      Rd('Wing Back', 'Defend', 'Keep Possession'),
      Rd('Wing Back', 'Support', 'Shuttle Ball'),
      P('MC', 'Spearhead Attacks Closer to Defence'),
      Rd('Deep Lying Playmaker', 'Defend', 'Keep Possession Away From Pressure'),
      Rd('Deep Lying Playmaker', 'Support', 'Shuttle Ball Into Space'),
      P('ML', 'Penetrate Gaps Intermittently'),
      P('AMC', 'Penetrate Gaps'),
      Rd('Advanced Playmaker', 'Attack', 'Create Chances Urgently'),
      Rd('Advanced Playmaker', 'Support', 'Shuttle Ball Through Defence'),
      R('Enganche', 'Force Half Chances'),
      R('Shadow Striker', 'Penetrate Gaps Persistently'),
      R('Trequartista', 'Force Half Chances'),
      P('AML', 'Penetrate Gaps Persistently'),
      Rd('Defensive Winger', 'Defend', 'Shuttle Ball Through Defence'),
      Rl('Advanced Forward', true, 'Draw Off Defenders'),
      Dul('Attack', false, 'Overload Defenders'),
      Rl('Defensive Forward', true, 'Suppress Counterattacking Options'),
      Rl('False Nine', true, 'Create Chances'),
      Rl('Trequartista', true, 'Force Half Chances'),
      Rl('Trequartista', false, 'Force Half Chances Without Hesitation')
    ],
    overload: [
      P('GK', 'Initiate Attacks'),
      Rd('Sweeper Keeper', 'Attack', 'Support Attacks'),
      Rd('Sweeper Keeper', 'Support', 'Initiate Attacks'),
      P('SW', 'Recover Possession Immediately'),
      Rd('Libero', 'Attack', 'Spearhead Attacks'),
      Rd('Libero', 'Support', 'Shuttle Ball'),
      P('DC', 'Keep Possession'),
      Du('Cover', 'Recover Possession'),
      Du('Stopper', 'Keep Possession Under Pressure'),
      P('DL', 'Spearhead Attacks Closer to Defence'),
      Du('Defend', 'Keep Possession Under Pressure'),
      Du('Support', 'Shuttle Ball Through Defence'),
      P('DM', 'Shuttle Ball Into Space'),
      R('Half Back', 'Keep Possession'),
      P('WBL', 'Penetrate Gaps'),
      Rd('Wing Back', 'Defend', 'Shuttle Ball'),
      Rd('Wing Back', 'Support', 'Create Chances'),
      P('MC', 'Penetrate Gaps Persistently'),
      Rd('Advanced Playmaker', 'Attack', 'Force Half Chances Without Hesitation'),
      Rd('Deep Lying Playmaker', 'Defend', 'Shuttle Ball Into Space'),
      Rd('Deep Lying Playmaker', 'Support', 'Create Chances Patiently'),
      P('ML', 'Draw Off Defenders'),
      P('AMC', 'Overload Defenders'),
      Rd('Advanced Playmaker', 'Support', 'Create Chances Urgently'),
      R('Enganche', 'Test Defence'),
      R('Trequartista', 'Test Defence'),
      P('AML', 'Challenge Defenders'),
      Rd('Defensive Winger', 'Defend', 'Suppress Counterattacking Outlets'),
      Rl('Advanced Forward', true, 'Bypass Last Defender'),
      Dul('Attack', false, 'Bypass Last Defender'),
      Rl('Defensive Forward', true, 'Isolate Advancing Midfielders'),
      Rl('False Nine', true, 'Force Half Chances'),
      Rl('Trequartista', true, 'Test Defence'),
      Rl('Trequartista', false, 'Test Defence With Power')
    ]
  };

  // ----------------------------------------------------------- STRUCTURED -----
  var STRUCTURED = {
    contain: [
      P('GK', 'Shield Goal'),
      R('Sweeper Keeper', 'Limit Pressure'),
      P('SW', 'Obstruct Shots'),
      R('Libero', 'Restrict Space Aggressively'),
      P('DC', 'Obstruct Shots'),
      Du('Stopper', 'Divert Attacking Movement'),
      P('DL', 'Divert Attacking Movement'),
      P('DM', 'Restrict Space Cautiously'),
      R('Half Back', 'Divert Attacking Movement'),
      P('WBL', 'Restrict Space'),
      P('MC', 'Disrupt Attacks'),
      R('Box to Box Midfielder', 'Disrupt Attacks Judiciously'),
      R('Deep Lying Playmaker', 'Restrict Space Cautiously'),
      Du('Defend', 'Restrict Space Aggressively'),
      P('ML', 'Disrupt Attacks Quickly'),
      P('AMC', 'Recover Possession After Defensive Transition'),
      R('Advanced Playmaker', 'Disrupt Attacks Quickly'),
      R('Shadow Striker', 'Recover Possession Immediately'),
      P('AML', 'Recover Possession'),
      Rl('Advanced Forward', true, 'Keep Possession'),
      Dul('Attack', false, 'Shuttle Ball'),
      Rl('False Nine', true, 'Recover Possession After Defensive Transition'),
      Dul('Support', false, 'Keep Possession Away From Pressure'),
      Rl('Trequartista', true, 'Recover Possession After Defensive Transition'),
      Rl('Trequartista', false, 'Keep Possession Away From Pressure')
    ],
    defensive: [
      P('GK', 'Limit Pressure'),
      R('Sweeper Keeper', 'Distribute Safely'),
      P('SW', 'Contain Attacking Movement'),
      R('Libero', 'Disrupt Attacks Quickly'),
      P('DC', 'Divert Attacking Movement'),
      Du('Cover', 'Contain Attacking Movement'),
      Du('Stopper', 'Restrict Space Aggressively'),
      P('DL', 'Restrict Space Aggressively'),
      P('DM', 'Disrupt Attacks Judiciously'),
      R('Half Back', 'Restrict Space'),
      P('WBL', 'Disrupt Attacks'),
      P('MC', 'Recover Possession'),
      R('Box to Box Midfielder', 'Recover Possession After Defensive Transition'),
      R('Deep Lying Playmaker', 'Disrupt Attacks Judiciously'),
      Du('Defend', 'Disrupt Attacks Quickly'),
      P('ML', 'Recover Possession Immediately'),
      P('AMC', 'Keep Possession Away From Pressure'),
      R('Advanced Playmaker', 'Recover Possession Immediately'),
      R('Shadow Striker', 'Keep Possession Under Pressure'),
      P('AML', 'Keep Possession'),
      Rl('Advanced Forward', true, 'Shuttle Ball'),
      Dul('Attack', false, 'Spearhead Attacks'),
      Rl('False Nine', true, 'Keep Possession Away From Pressure'),
      Dul('Support', false, 'Shuttle Ball Into Space'),
      Rl('Trequartista', true, 'Keep Possession Away From Pressure'),
      Rl('Trequartista', false, 'Shuttle Ball Into Space')
    ],
    counter: [
      P('GK', 'Limit Pressure'),
      R('Sweeper Keeper', 'Cycle Possession'),
      P('SW', 'Restrict Space Cautiously'),
      R('Libero', 'Recover Possession'),
      P('DC', 'Restrict Space'),
      Du('Cover', 'Divert Attacking Movement'),
      Du('Stopper', 'Disrupt Attacks Judiciously'),
      P('DL', 'Disrupt Attacks'),
      P('DM', 'Disrupt Attacks Quickly'),
      R('Half Back', 'Disrupt Attacks Judiciously'),
      P('WBL', 'Recover Possession After Defensive Transition'),
      P('MC', 'Keep Possession Away From Pressure'),
      R('Box to Box Midfielder', 'Recover Possession Immediately'),
      R('Deep Lying Playmaker', 'Disrupt Attacks Quickly'),
      Du('Defend', 'Recover Possession'),
      P('ML', 'Keep Possession'),
      P('AMC', 'Keep Possession Under Pressure'),
      R('Advanced Playmaker', 'Keep Possession Away From Pressure'),
      R('Shadow Striker', 'Shuttle Ball'),
      P('AML', 'Shuttle Ball Into Space'),
      Rl('Advanced Forward', true, 'Spearhead Attacks from the Hole'),
      Dul('Attack', false, 'Create Chances Urgently'),
      Rl('Defensive Forward', true, 'Suppress Counterattacking Options'),
      Rl('False Nine', true, 'Keep Possession Under Pressure'),
      Dul('Support', false, 'Shuttle Ball'),
      Rl('Trequartista', true, 'Keep Possession Under Pressure'),
      Rl('Trequartista', false, 'Shuttle Ball')
    ],
    standard: [
      P('GK', 'Distribute Safely'),
      R('Sweeper Keeper', 'Cycle Possession'),
      P('SW', 'Restrict Space'),
      R('Libero', 'Keep Possession Away From Pressure'),
      P('DC', 'Disrupt Attacks Judiciously'),
      Du('Cover', 'Restrict Space'),
      Du('Stopper', 'Disrupt Attacks Quickly'),
      P('DL', 'Recover Possession After Defensive Transition'),
      P('DM', 'Recover Possession'),
      R('Half Back', 'Disrupt Attacks Quickly'),
      P('WBL', 'Recover Possession Immediately'),
      P('MC', 'Keep Possession Under Pressure'),
      R('Box to Box Midfielder', 'Keep Possession'),
      R('Deep Lying Playmaker', 'Recover Possession'),
      Du('Defend', 'Keep Possession Away From Pressure'),
      P('ML', 'Shuttle Ball Into Space'),
      P('AMC', 'Shuttle Ball'),
      R('Advanced Playmaker', 'Keep Possession Under Pressure'),
      R('Shadow Striker', 'Spearhead Attacking Moves from the Hole'),
      P('AML', 'Shuttle Ball Through Defence'),
      Rl('Advanced Forward', true, 'Spearhead Attacking Moves Closer to Defence'),
      Dul('Attack', false, 'Penetrate Gaps'),
      Rl('Defensive Forward', true, 'Suppress Counterattacking Outlets'),
      Rl('Defensive Forward', false, 'Suppress Counterattacking Options'),
      Rl('False Nine', true, 'Shuttle Ball'),
      Dul('Support', true, 'Create Chances Urgently'),
      Dul('Support', false, 'Create Chances Patiently'),
      Rl('Trequartista', true, 'Shuttle Ball'),
      Rl('Trequartista', false, 'Create Chances Patiently')
    ],
    control: [
      P('GK', 'Distribute Safely'),
      R('Sweeper Keeper', 'Initiate Attacks'),
      P('SW', 'Disrupt Attacks Judiciously'),
      R('Libero', 'Keep Possession Under Pressure'),
      P('DC', 'Disrupt Attacks Quickly'),
      Du('Cover', 'Disrupt Attacks Judiciously'),
      Du('Stopper', 'Recover Possession'),
      P('DL', 'Recover Possession Immediately'),
      P('DM', 'Keep Possession Away From Pressure'),
      R('Half Back', 'Recover Possession'),
      P('WBL', 'Keep Possession'),
      P('MC', 'Shuttle Ball'),
      R('Box to Box Midfielder', 'Shuttle Ball Into Space'),
      R('Deep Lying Playmaker', 'Keep Possession Away From Pressure'),
      Du('Defend', 'Keep Possession Under Pressure'),
      P('ML', 'Shuttle Ball Through Defence'),
      P('AMC', 'Spearhead Attacking Moves from the Hole'),
      R('Advanced Playmaker', 'Shuttle Ball Through Defence'),
      R('Shadow Striker', 'Spearhead Attacking Moves Closer to Defence'),
      Du('Support', 'Create Chances'),
      P('AML', 'Spearhead Attacking Moves'),
      Rd('Defensive Winger', 'Defend', 'Suppress Counterattacks'),
      Rl('Advanced Forward', true, 'Penetrate Gaps'),
      Dul('Attack', false, 'Draw Off Defenders'),
      Rl('Defensive Forward', true, 'Isolate Midfielders'),
      Rl('Defensive Forward', false, 'Suppress Counterattacking Outlets'),
      Rl('False Nine', true, 'Create Chances'),
      Rl('Trequartista', true, 'Create Chances'),
      Rl('Trequartista', false, 'Create Chances Urgently')
    ],
    attacking: [ // guide labels "ATTACK" under Structured
      P('GK', 'Cycle Possession'),
      R('Sweeper Keeper', 'Initiate Attacks'),
      P('SW', 'Disrupt Attacks Quickly'),
      R('Libero', 'Shuttle Ball'),
      P('DC', 'Recover Possession'),
      Du('Cover', 'Disrupt Attacks'),
      Du('Stopper', 'Recover Possession Immediately'),
      P('DL', 'Keep Possession'),
      P('DM', 'Keep Possession Under Pressure'),
      R('Half Back', 'Keep Possession Away From Pressure'),
      P('WBL', 'Shuttle Ball Into Space'),
      P('MC', 'Spearhead Attacking Moves from the Hole'),
      R('Box to Box Midfielder', 'Shuttle Ball Through Defence'),
      R('Deep Lying Playmaker', 'Keep Possession Under Pressure'),
      Du('Defend', 'Suppress Counterattacks'),
      Du('Support', 'Create Chances'),
      P('ML', 'Spearhead Attacking Moves'),
      P('AMC', 'Spearhead Attacking Moves Closer to Defence'),
      R('Advanced Playmaker', 'Create Chances Patiently'),
      R('Shadow Striker', 'Penetrate Gaps'),
      P('AML', 'Penetrate Gaps Intermittently'),
      Rd('Defensive Winger', 'Defend', 'Isolate Advancing Midfielders'),
      Rl('Advanced Forward', true, 'Draw Off Defenders'),
      Dul('Attack', false, 'Overload Defenders'),
      Rl('Defensive Forward', true, 'Hassle Dawdling Defenders'),
      Rl('Defensive Forward', false, 'Isolate Advancing Midfielders'),
      Rl('False Nine', true, 'Force Half Chances'),
      Rl('Trequartista', true, 'Force Half Chances'),
      Rl('Trequartista', false, 'Force Half Chances When Necessary')
    ],
    overload: [
      P('GK', 'Initiate Attacks'),
      R('Sweeper Keeper', 'Support Attacks'),
      P('SW', 'Recover Possession Immediately'),
      Rd('Libero', 'Attack', 'Spearhead Attacking Moves'),
      Rd('Libero', 'Support', 'Create Chances'),
      P('DC', 'Keep Possession'),
      Du('Cover', 'Keep Possession Under Pressure'),
      Du('Stopper', 'Recover Possession'),
      P('DL', 'Shuttle Ball'),
      P('DM', 'Shuttle Ball Through Defence'),
      R('Half Back', 'Shuttle Ball Into Space'),
      P('WBL', 'Spearhead Attacking Moves from the Hole'),
      Du('Defend', 'Suppress Counterattacking Options'),
      Du('Support', 'Create Chances Patiently'),
      P('MC', 'Penetrate Gaps Intermittently'),
      R('Advanced Playmaker', 'Force Half Chances When Necessary'),
      R('Box to Box Midfielder', 'Create Chances Urgently'),
      R('Deep Lying Playmaker', 'Shuttle Ball Through Defence'),
      P('ML', 'Penetrate Gaps'),
      P('AMC', 'Penetrate Gaps Persistently'),
      R('Enganche', 'Force Half Chances Without Hesitation'),
      R('Shadow Striker', 'Draw Off Defenders'),
      R('Trequartista', 'Force Half Chances Without Hesitation'),
      P('AML', 'Draw Off Defenders'),
      Rd('Defensive Winger', 'Defend', 'Hassle Dawdling Defenders'),
      Rl('Advanced Forward', true, 'Bypass Last Defender'),
      Dul('Attack', false, 'Bypass Last Defender'),
      Rl('Defensive Forward', true, 'Force Clearance'),
      Rl('Defensive Forward', false, 'Hassle Dawdling Defenders'),
      Rl('False Nine', true, 'Test Defence'),
      Rl('Trequartista', true, 'Test Defence'),
      Rl('Trequartista', false, 'Test Defence With Precision')
    ]
  };

  // ---------------------------------------------------- HIGHLY STRUCTURED -----
  var HIGHLY = {
    contain: [
      P('GK', 'Shield Goal'),
      R('Sweeper Keeper', 'Limit Pressure'),
      P('SW', 'Obstruct Shots'),
      R('Libero', 'Restrict Space Cautiously'),
      P('DC', 'Obstruct Shots'),
      Du('Stopper', 'Contain Attacking Movement'),
      P('DL', 'Slow Attacking Movement'),
      P('DM', 'Divert Attacking Movement'),
      R('Half Back', 'Contain Attacking Movement'),
      P('WBL', 'Divert Attacking Movement'),
      P('MC', 'Disrupt Attacks Judiciously'),
      R('Box to Box Midfielder', 'Restrict Space Aggressively'),
      R('Deep Lying Playmaker', 'Restrict Space Cautiously'),
      Du('Defend', 'Restrict Space'),
      P('ML', 'Disrupt Attacks Judiciously'),
      P('AMC', 'Disrupt Attacks Quickly'),
      R('Advanced Playmaker', 'Disrupt Attacks Judiciously'),
      R('Shadow Striker', 'Recover Possession'),
      P('AML', 'Disrupt Attacks Quickly'),
      Rl('Advanced Forward', true, 'Recover Possession Immediately'),
      Dul('Attack', false, 'Keep Possession Under Pressure'),
      Dul('Support', false, 'Recover Possession'),
      Dul('Defend', false, 'Recover Possession'),
      Rl('False Nine', true, 'Disrupt Attacks Quickly'),
      Rl('Trequartista', true, 'Disrupt Attacks Quickly'),
      Rl('Trequartista', false, 'Recover Possession Immediately')
    ],
    defensive: [
      P('GK', 'Limit Pressure'),
      R('Sweeper Keeper', 'Distribute Safely'),
      P('SW', 'Contain Attacking Movement'),
      R('Libero', 'Disrupt Attacks Judiciously'),
      P('DC', 'Divert Attacking Movement'),
      Du('Cover', 'Contain Attacking Movement'),
      Du('Stopper', 'Restrict Space Aggressively'),
      P('DL', 'Restrict Space Cautiously'),
      P('DM', 'Restrict Space Aggressively'),
      R('Half Back', 'Restrict Space'),
      P('WBL', 'Restrict Space Aggressively'),
      P('MC', 'Recover Possession After Defensive Transition'),
      R('Box to Box Midfielder', 'Disrupt Attacks Quickly'),
      R('Deep Lying Playmaker', 'Disrupt Attacks Judiciously'),
      Du('Defend', 'Disrupt Attacks'),
      P('ML', 'Recover Possession After Defensive Transition'),
      P('AMC', 'Recover Possession Immediately'),
      R('Advanced Playmaker', 'Recover Possession'),
      R('Shadow Striker', 'Keep Possession'),
      P('AML', 'Recover Possession Immediately'),
      Rl('Advanced Forward', true, 'Keep Possession Under Pressure'),
      Dul('Attack', false, 'Shuttle Ball Through Defence'),
      Dul('Support', false, 'Keep Possession'),
      Dul('Defend', false, 'Keep Possession'),
      Rl('False Nine', true, 'Recover Possession Immediately'),
      Rl('Trequartista', true, 'Recover Possession Immediately'),
      Rl('Trequartista', false, 'Keep Possession Under Pressure')
    ],
    counter: [
      P('GK', 'Limit Pressure'),
      R('Sweeper Keeper', 'Cycle Possession'),
      P('SW', 'Restrict Space Cautiously'),
      R('Libero', 'Recover Possession After Defensive Transition'),
      P('DC', 'Restrict Space Aggressively'),
      Du('Cover', 'Restrict Space Cautiously'),
      Du('Stopper', 'Disrupt Attacks'),
      P('DL', 'Disrupt Attacks Judiciously'),
      P('DM', 'Disrupt Attacks Quickly'),
      R('Half Back', 'Disrupt Attacks Judiciously'),
      P('WBL', 'Disrupt Attacks Quickly'),
      P('MC', 'Keep Possession Away From Pressure'),
      R('Box to Box Midfielder', 'Recover Possession Immediately'),
      R('Deep Lying Playmaker', 'Disrupt Attacks Quickly'),
      Du('Defend', 'Recover Possession'),
      P('ML', 'Keep Possession Away From Pressure'),
      P('AMC', 'Keep Possession Under Pressure'),
      R('Advanced Playmaker', 'Keep Possession Away From Pressure'),
      R('Shadow Striker', 'Shuttle Ball'),
      P('AML', 'Keep Possession Under Pressure'),
      Rl('Advanced Forward', true, 'Shuttle Ball Through Defence'),
      Dul('Attack', false, 'Spearhead Attacking Moves'),
      Dul('Support', false, 'Shuttle Ball Into Space'),
      Dul('Defend', false, 'Shuttle Ball Into Space'),
      Rl('False Nine', true, 'Keep Possession Under Pressure'),
      Rl('Trequartista', true, 'Keep Possession Under Pressure'),
      Rl('Trequartista', false, 'Shuttle Ball')
    ],
    standard: [
      P('GK', 'Distribute Safely'),
      R('Sweeper Keeper', 'Cycle Possession'),
      P('SW', 'Restrict Space Aggressively'),
      R('Libero', 'Recover Possession Immediately'),
      P('DC', 'Disrupt Attacks'),
      Du('Cover', 'Restrict Space Aggressively'),
      Du('Stopper', 'Recover Possession After Defensive Transition'),
      P('DL', 'Disrupt Attacks Quickly'),
      P('DM', 'Recover Possession'),
      R('Half Back', 'Disrupt Attacks Quickly'),
      P('WBL', 'Recover Possession'),
      P('MC', 'Keep Possession Under Pressure'),
      R('Box to Box Midfielder', 'Keep Possession'),
      R('Deep Lying Playmaker', 'Recover Possession'),
      Du('Defend', 'Keep Possession Away From Pressure'),
      P('ML', 'Keep Possession Under Pressure'),
      P('AMC', 'Shuttle Ball'),
      R('Advanced Playmaker', 'Keep Possession Under Pressure'),
      R('Shadow Striker', 'Spearhead Attacking Moves from the Hole'),
      P('AML', 'Shuttle Ball'),
      Rl('Advanced Forward', true, 'Spearhead Attacking Moves'),
      Dul('Attack', false, 'Penetrate Gaps Intermittently'),
      Dul('Support', false, 'Shuttle Ball Through Defence'),
      Dul('Defend', false, 'Shuttle Ball Through Defence'),
      Rl('False Nine', true, 'Shuttle Ball'),
      Rl('Trequartista', true, 'Shuttle Ball'),
      Rl('Trequartista', false, 'Create Chances Patiently')
    ],
    control: [
      P('GK', 'Cycle Possession'),
      R('Sweeper Keeper', 'Initiate Attacks'),
      P('SW', 'Disrupt Attacks'),
      R('Libero', 'Keep Possession'),
      P('DC', 'Recover Possession After Defensive Transition'),
      Du('Cover', 'Disrupt Attacks'),
      Du('Stopper', 'Recover Possession Immediately'),
      P('DL', 'Recover Possession'),
      P('DM', 'Keep Possession Away From Pressure'),
      R('Half Back', 'Recover Possession'),
      P('WBL', 'Keep Possession Away From Pressure'),
      P('MC', 'Shuttle Ball'),
      R('Box to Box Midfielder', 'Shuttle Ball Into Space'),
      R('Deep Lying Playmaker', 'Keep Possession Away From Pressure'),
      Du('Defend', 'Keep Possession Under Pressure'),
      P('ML', 'Shuttle Ball'),
      P('AMC', 'Spearhead Attacking Moves from the Hole'),
      R('Advanced Playmaker', 'Shuttle Ball'),
      R('Shadow Striker', 'Spearhead Attacking Moves Closer to Defence'),
      Du('Support', 'Create Chances Patiently'),
      P('AML', 'Spearhead Attacking Moves from the Hole'),
      Rd('Defensive Winger', 'Defend', 'Suppress Counterattacking Options'),
      Rl('Advanced Forward', true, 'Penetrate Gaps Intermittently'),
      Dul('Attack', false, 'Penetrate Gaps Persistently'),
      Rl('Defensive Forward', true, 'Isolate Advancing Midfielders'),
      Rl('Defensive Forward', false, 'Suppress Counterattacks'),
      Rl('False Nine', true, 'Create Chances'),
      Rl('Trequartista', true, 'Create Chances'),
      Rl('Trequartista', false, 'Create Chances Urgently')
    ],
    attacking: [
      P('GK', 'Cycle Possession'),
      R('Sweeper Keeper', 'Initiate Attacks'),
      P('SW', 'Recover Possession'),
      R('Libero', 'Shuttle Ball'),
      P('DC', 'Keep Possession Away From Pressure'),
      Du('Cover', 'Recover Possession After Defensive Transition'),
      Du('Stopper', 'Keep Possession'),
      P('DL', 'Keep Possession'),
      P('DM', 'Shuttle Ball Into Space'),
      R('Half Back', 'Keep Possession'),
      P('WBL', 'Shuttle Ball Into Space'),
      P('MC', 'Spearhead Attacking Moves'),
      R('Box to Box Midfielder', 'Create Chances Patiently'),
      R('Deep Lying Playmaker', 'Shuttle Ball Into Space'),
      Du('Defend', 'Suppress Counterattacks'),
      Du('Support', 'Create Chances'),
      P('ML', 'Spearhead Attacking Moves'),
      P('AMC', 'Penetrate Gaps Intermittently'),
      R('Advanced Playmaker', 'Create Chances Urgently'),
      R('Enganche', 'Force Half Chances When Necessary'),
      R('Shadow Striker', 'Penetrate Gaps'),
      R('Trequartista', 'Force Half Chances When Necessary'),
      P('AML', 'Penetrate Gaps Intermittently'),
      Rd('Defensive Winger', 'Defend', 'Isolate Advancing Midfielders'),
      Rl('Advanced Forward', true, 'Draw Off Defenders'),
      Dul('Attack', false, 'Overload Defenders'),
      Rl('Defensive Forward', true, 'Hassle Dawdling Defenders'),
      Rl('Defensive Forward', false, 'Isolate Advancing Midfielders'),
      Rl('False Nine', true, 'Force Half Chances'),
      Rl('Trequartista', true, 'Force Half Chances'),
      Rl('Trequartista', false, 'Force Half Chances')
    ],
    overload: [
      P('GK', 'Initiate Attacks'),
      R('Sweeper Keeper', 'Support Attacks'),
      P('SW', 'Keep Possession'),
      Rd('Libero', 'Attack', 'Spearhead Attacking Moves'),
      Rd('Libero', 'Support', 'Create Chances'),
      P('DC', 'Shuttle Ball Into Space'),
      Du('Cover', 'Keep Possession Away From Pressure'),
      Du('Stopper', 'Shuttle Ball'),
      P('DL', 'Shuttle Ball'),
      P('DM', 'Create Chances Patiently'),
      R('Half Back', 'Shuttle Ball'),
      P('WBL', 'Spearhead Attacking Moves from the Hole'),
      Du('Defend', 'Suppress Counterattacking Options'),
      Du('Support', 'Create Chances Patiently'),
      P('MC', 'Penetrate Gaps'),
      R('Advanced Playmaker', 'Force Half Chances'),
      R('Box to Box Midfielder', 'Force Half Chances When Necessary'),
      R('Deep Lying Playmaker', 'Create Chances Patiently'),
      P('ML', 'Penetrate Gaps'),
      P('AMC', 'Draw Off Defenders'),
      R('Enganche', 'Test Defence With Precision'),
      R('Shadow Striker', 'Overload Defenders'),
      R('Trequartista', 'Test Defence With Precision'),
      P('AML', 'Draw Off Defenders'),
      Rd('Defensive Winger', 'Defend', 'Hassle Dawdling Defenders'),
      Rl('Advanced Forward', true, 'Bypass Last Defender'),
      Dul('Attack', false, 'Bypass Last Defender'),
      Rl('Defensive Forward', true, 'Force Clearance'),
      Rl('Defensive Forward', false, 'Hassle Dawdling Defenders'),
      Rl('False Nine', true, 'Test Defence'),
      Rl('Trequartista', true, 'Test Defence'),
      Rl('Trequartista', false, 'Test Defence')
    ]
  };

  global.RESPONSIBILITIES.registerResp('fluid', FLUID);
  global.RESPONSIBILITIES.registerResp('flexible', FLEXIBLE);
  global.RESPONSIBILITIES.registerResp('structured', STRUCTURED);
  global.RESPONSIBILITIES.registerResp('highly structured', HIGHLY);
})(window);
